const $=s=>document.querySelector(s),music=$('#music'),toggle=$('#music-toggle');
function audioState(){toggle.setAttribute('aria-pressed',String(!music.paused));toggle.setAttribute('aria-label',music.paused?'Reproducir música':'Pausar música');toggle.textContent=music.paused?'♫':'Ⅱ'}
async function play(){try{await music.play();$('#audio-status').textContent=''}catch{$('#audio-status').textContent='Toca ♫ para escuchar la música.'}audioState()}
$('#enter').addEventListener('click',()=>{$('#cover').hidden=true;$('#invitation').hidden=false;window.scrollTo(0,0);play();document.title='Abby Adriana · Mis 15';});
toggle.addEventListener('click',()=>{if(music.paused)play();else music.pause()});music.addEventListener('play',audioState);music.addEventListener('pause',audioState);
const reduce=matchMedia('(prefers-reduced-motion: reduce)');let off=reduce.matches;
function effects(){document.body.classList.toggle('effects-off',off);$('#effects').setAttribute('aria-pressed',String(off));$('#effects').setAttribute('aria-label',off?'Activar destellos':'Pausar destellos')}
effects();$('#effects').addEventListener('click',()=>{off=!off;effects()});
const target=new Date('2026-10-24T17:00:00-04:00');function countdown(){const remaining=Math.max(0,target-Date.now()),s=Math.floor(remaining/1000);[['days',Math.floor(s/86400)],['hours',Math.floor(s/3600)%24],['minutes',Math.floor(s/60)%60],['seconds',s%60]].forEach(([id,n])=>$('#'+id).textContent=String(n).padStart(2,'0'));if(!remaining)$('#countdown-note').textContent='¡Llegó el día de celebrar!'}countdown();setInterval(countdown,1000);
const address='Av. General Bilbao, casa N.º 70. Media cuadra antes de llegar al cuartel Cotapachi. Referencia: Casa Táctica.';
$('#copy-address').addEventListener('click',async()=>{try{await navigator.clipboard.writeText(address);$('#copy-result').textContent='Dirección copiada ✓'}catch{$('#copy-result').textContent=address}});
if('IntersectionObserver' in window){const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');observer.unobserve(e.target)}}),{threshold:.08});document.querySelectorAll('.reveal').forEach(e=>{e.classList.add('ready');observer.observe(e)})}
// Mirror tiles are projected onto a sphere to give the disco balls curved reflections.
document.querySelectorAll('.disco').forEach((ball,b)=>{let tiles='';for(let y=-9;y<9;y++){let ya=y/9,yb=(y+1)/9;for(let x=-12;x<12;x++){let a=x*Math.PI/24,c=(x+1)*Math.PI/24;let r1=Math.sqrt(1-ya*ya),r2=Math.sqrt(1-yb*yb);const shade=45+Math.round(((x*17+y*31+b*7+800)%17)/17*47);let hue=ball.classList.contains('pink')?333:265,sat=ball.classList.contains('pink')?37:5;tiles+=`<path d="M${100+97*r1*Math.sin(a)},${100+97*ya} L${100+97*r1*Math.sin(c)},${100+97*ya} L${100+97*r2*Math.sin(c)},${100+97*yb} L${100+97*r2*Math.sin(a)},${100+97*yb}Z" fill="hsl(${hue} ${sat}% ${shade}%)" stroke="#fffb" stroke-width=".6"/>`}}ball.innerHTML=`<svg viewBox="0 0 200 200" aria-hidden="true"><defs><radialGradient id="shine${b}" cx="30%" cy="20%" r="85%"><stop stop-color="#fff" stop-opacity=".75"/><stop offset=".4" stop-color="#fff" stop-opacity="0"/><stop offset="1" stop-color="#26112b" stop-opacity=".65"/></radialGradient></defs><circle cx="100" cy="100" r="98" fill="#dbc9d7"/>${tiles}<circle cx="100" cy="100" r="98" fill="url(#shine${b})"/></svg>`});
for(let i=0;i<34;i++){const spark=document.createElement('i');spark.style.cssText=`--x:${(i*37.7)%100}%;--y:${(i*23.3)%100}%;--size:${16+(i%5)*8}px;--duration:${4.4+(i%6)*.7}s;--delay:-${i*.47}s`;$('#lights').append(spark)}
